### ISSUE TITLE
When saving json, if extension is not included, file is not saved

### ISSUE THREAD

**Issue by markstock** [Applied-Scientific-Research/Omega2D#12]
On Windows, when saving the simulation setup to json, if the user does not type the `.json` file extension, the file is not saved anywhere (or it is, but just as `output.json`. Can we check for the correct extension and add it if necessary?

**Comment by BHill96** [comment]
ImguiWindowsFileIO searches for the file extension based on the current file name, but since their initial file name doesn't have a file extension it returns nothing, resulting in the file path being whatever is given to the window from main_gui, which in this case is output.json.
