### ISSUE TITLE
Line of emitters is not working

### ISSUE THREAD

**Issue by markstock** [Applied-Scientific-Research/Omega2D#48]
Line of emitters doesn't seem to be working. Attached file draws the emitter points, and it seems that points are being created, but they are not moving. Also, there's a point at the origin.

Argh, can't attach json files here. See the Discord window.

**Comment by BHill96** [comment]
reopened just to test a GitHub feature

**Comment by markstock** [comment]
Also, not sure why this fix wasn't in master. d8c1195c459d0a47a8a6a0ca4893b6c3161156bd
